### PR TITLE
Update fieldtrip_oddball_OPM_pipeline.ipynb

### PR DESCRIPTION
**Pull request by contsili**
Commit 425e4ae
- Added strategy 1 at the section:  "Coregister MRI with headshape"
- Edited the section: "Read Headshape from Polhemus Laser-scan"
- Added more titles to organise the notebook better.

Commit 4162d7a
- Added Dipole fitting
- Added suggestions for cleaning data

### CODE REVIEW

**Comment by hzaatiti-NYU** [comment]
thank you,

can you provide screenshots within the notebook of the alignment for strategy 1 and strategy 2

**Comment by hzaatiti-NYU** [comment]
for the dipole fitting, ideally we would like to fit two dipoles on each hemisphere, can we attempt this? I understand the data is noisy but we can provide the code for that?
Would also love more details on the fitting results, what is the position of the dipole? what is the orientation? how can we get the value of the measured activity? Comments on the below plot? is it a visualisation of the dipole location?
image


> instead of using cfg.layout = 'fieldlinebeta2bz_helmet.mat'; we can maybe use the layout given by the .fif? ANSWER: No
Why no? the .fif has the layout for the sensor at acquisition time

**Comment by contsili** [comment]
I checked the sensor topographies and I believe that we can not fit the dipole on the right and left hemisphere 100 ms post-stimulus. More cleaning is required. I can apply Homogeneous Field Correction and see how the signal improves. Can you let me know to what extent the participant moved its head during the experiment? Head movement will be more challenging to denoise. For reference, at the Donders we have mounted the helmet on a wooden plate to keep the participants head fixed. 

I will provide a figure where you can see clearly where the dipole is fitted.

The function, e.g., ft_topoplotER, automatically gets from the .fif file where the locations of the OPMs are. I think it does that through the field "grad" that is in your timelock structure. cfg.layout is then only used for the 2D visualization of the sensor topographies.

**Comment by hzaatiti-NYU** [comment]
I added a few extra things and plots for MRI coregistration with headshape, please check my other pull request  #43 , and merge the two branches together if you satisfied

**Comment by hzaatiti-NYU** [comment]
> I checked the sensor topographies and I believe that we can not fit the dipole on the right and left hemisphere 100 ms post-stimulus. More cleaning is required. I can apply Homogeneous Field Correction and see how the signal improves. Can you let me know to what extent the participant moved its head during the experiment? Head movement will be more challenging to denoise. For reference, at the Donders we have mounted the helmet on a wooden plate to keep the participants head fixed.
>


Head movement should be minimal during the experiment because the helmet allows pushing the sensors in, but we do not have an accurate method to measure head movement.
 
> I will provide a figure where you can see clearly where the dipole is fitted.
> 
> The function, e.g., ft_topoplotER, automatically gets from the .fif file where the locations of the OPMs are. I think it does that through the field "grad" that is in your timelock structure. cfg.layout is then only used for the 2D visualization of the sensor topographies.

Can you add any details that shows how you evaluated that the data is noisy? It is important to show how you were visually able to tell the data is noisy and your opinion on what kind of noise it is thank you.

**Comment by hzaatiti-NYU** [comment]
Can you add any details that shows how you evaluated that the data is noisy? It is important to show how you were visually able to tell the data is noisy and your opinion on what kind of noise it is thank you, and how can users have measurements for noise levels and so on (Not necessarily in details just how were you able to see it and your opinion on it :) )

**Comment by hzaatiti-NYU** [comment]
I have a question about picking fiducials Left ear/Right ear from MRI, in your lab how would you know which part is left and which is right? is there a convention that you follow?

**Comment by contsili** [comment]
I merged #43.

Also, I added a figure for MRI coregistration with headshape based on strategy 2. Note that I keep the nose as part of the headshape. The nose from the headshape "grabs" on the nose from the MRI and improves the ICP. Without the nose, the headshape is pretty round and the ICP might rotate it in relation to the MRI.

**Comment by contsili** [comment]
> I have a question about picking fiducials Left ear/Right ear from MRI, in your lab how would you know which part is left and which is right? is there a convention that you follow?

In the lab we have a CTF SQUID system. In the conversion of the MRI from DICOM to the CTF format, it is tricky to keep left and right correct. Therefore, we use a vitamin-E capsule near the right ear while making the anatomical MRI (Note that we also have two more vitamin-E capsules marking the left and right preauricular points, so in total 3 vitamin-E capsules). That way we always know where the right side is. 

For more info see: https://www.fieldtriptoolbox.org/faq/how_can_i_convert_an_anatomical_mri_from_dicom_into_ctf_format/
Capture

**Comment by contsili** [comment]
Commit 3993b8d2
- Added sensor level analysis
- Made a separate section about noise

**Comment by hzaatiti-NYU** [comment]
I'll fix the doc build tomorrow morning and merge
Thanks for the hard work!

**Pull request merged**
