### PR TITLE
Dashboard updating continues

### PR DESCRIPTION
**Pull request by Hzaatiti**

### CODE REVIEW

**Comment by Hzaatiti** [comment]
@EmnaTay I noticed that the average value from the .con looks wrong. 
Typically a MEG signal is in the 100 femto Tesla. 
Can we please check the average values ?

**Comment by Hzaatiti** [comment]
@EmnaTay also when we are computing the average and variance, we must filter the channels to the squid sensors channels only 1 to 207 and excluse 92 (broken sensor), 
Please add this a channel picking using the mne library

**Comment by Hzaatiti** [comment]
Hi Emna, amazing work, this is looking great!

- I tested locally box_script, works well 
- tested processing_con_files_for_tables generation works well

Next tasks:

- merge 9-dashboard and dashboards, have the code in a separate directory than the .rst, for example called "dashboard_generation_scripts"
- address remarks on the scripts
- check if there's a way to retrieve the "Date modified" field, which usually, indicates the time this data has been generated by the KIT system, use this field for the time from now on instead of file name  (Note: if this is too tricky to do, please skip this task)
- have two separate plots for variance and mean, or use different scales on the same plot (i prefer two separate plots, up to you)
- could be tricky to do: as new .con files are generated, we would like to keep the old values we have and not recompute them, and not download the old .con files, but download only the new .con files for which we haven't computed the metrics yet, and then compute metrics, update the .csv and the graph with the new entries. Let us think of a way to do this, as the .con can be heavy downloads and will slow down the build speed. I am not sure if readthedocs keep the files or not after downloading, if it keeps the files ==> only download the missing ones, if it doesn't keep the files ==> we can just ignore this for now
- test box_script when added to conf.py, check if the secrets are being used correctly, add proper error handling through "logging" for this script

**Comment by EmnaTay** [comment]
Ready for review:

-Now using metadata we can get the date "last-modified" for each .con file: In the script i add the date and time to the front of the name of the file and separate them with "_"

-Also we only download files that have been added/ modified after the last file that have been downloaded

- Added error handling into the box-script

-As for the graphs, the average and variance have different  graphs, eliminated the channels that shouldn't be taken into account, ( x-axis for time y-axis for variance /average ) but I find the graphs to be a little weird looking I am not sure that it's correct or not.

-Merged the dashboards into 9-dashboards.

-Added a field for details for the table table statistics.

**Comment by Hzaatiti** [comment]
Great work @EmnaTay 
Lets discuss during the week, I will put some note for myself here don't address the ones in the draft section

Draft notes:



Next Tasks notes:

**Comment by EmnaTay** [comment]
Ready for review:

- added zero's channel check
- checked directory for convert-csv-to-rst.py
- created a RTD account 
- removed the lines from the plots
- created a separate plot for OPM data for the .fifo files

**Comment by Hzaatiti** [comment]
Hi Emna, great job!

- lets try to make box_script.py run successfully on RTD, maybe add in the log what are the files that are downloaded does the server keeps the .con files or does it download them everytime again?
- then test the whole process from computing the metrics from the downloaded .con, updating the .csv file, generating the .md, and displaying the output, remove one .con from emptyroom, reset the dashboards, generate an initial dashboard, add the .con and check that the csv is updated and the dashboard is updated
- investigate why the average is negative? check the unit of display it should be in fT  (femtoTesla or pT picoTesla)

**Comment by Hzaatiti** [comment]
RTD build is fixed for your fork
the error to fix now is this one

image

Let us see how we can fix this :)

**Comment by EmnaTay** [comment]
Screenshot 2024-08-21 234428
Hello! I am unable to access the admin settings on the RTD, I am not sure how to make a rebuild or to force a rebuild, the build runs successfully on the PR but i can't see the details of the build, I would really appreciate it if you told me where I can access those details. Thanks in advance !

**Comment by Hzaatiti** [comment]
Tasks for next time:

- Let us prepare a documentation on your work, that will serve for a presentation during september with the results of your internship

**Comment by EmnaTay** [comment]
Okay, well received.

**Comment by EmnaTay** [comment]
Hello Dr. Hadi,

I hope you're doing well! I've completed most of the documentation and would really appreciate it if you could take a look and provide your feedback.

Thank you in advance !

**Comment by Hzaatiti** [comment]
@Hzaatiti TODO:
- test computation of FFT, check plots, define a threshold scheme
- Clean Overall systems dashboard
- Check the values of the average and variance and mean

@EmnaTay TODO:
- push the final version of your code
- cleanup the unused dashboard plots and restructure
- Identify where is the date error coming from, if it is too tricky to fix, lets just go with the name of the file

**Comment by Hzaatiti** [comment]
#50 issue araised while testing the box_script.py without limits on the file_limit variable

**Pull request merged**
